dojo.provide("calitha.collections");
dojo.require("calitha.collections._base");
dojo.require("calitha.collections.ArrayList");
dojo.require("calitha.collections.LinkedList");
dojo.require("calitha.collections.HashSet");
dojo.require("calitha.collections.TreeSet");
dojo.require("calitha.collections.HashMap");
dojo.require("calitha.collections.TreeMap");
dojo.require("calitha.collections.Dictionary");
